server:
  port: 8032
spring:
  application:
    name: microsoftservice-gateway-zuul
eureka:
  client:
    serviceUrl:    
      defaultZone: http://user:password123@localhost:8761/eureka/ 
  instance:
    prefer-ip-address: true
    metadata-map:  
      data: 我的自定义元数据movie 
zuul:  
  host:  
    socket-timeout-millis: 60000  
    connect-timeout-millis: 60000 
hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 60000 
ribbon:  
  ReadTimeout: 100000  
  ConnectTimeout: 100000 

  