server: 
  port: 8080
spring: 
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/752143639/spring-cloud/  # 配置Git仓库的地址
         # label: dev
          username: 75243639@qq.com                                                
          password: lfq2760521 
