server: 
  port: 8033
eureka:
  client:
    serviceUrl:    
      defaultZone: http://user:password123@localhost:8761/eureka/ 
  instance:
    prefer-ip-address: true
    metadata-map:  
      data: 我的自定义元数据movie
spring:
  application:
    name: microservice-file-upload
  http:
    multipart: 
      max-file-size: 2000Mb      # Max file size，默认1M
      max-request-size: 2500Mb   # Max request size，默认10M