server:
  port: 8031
spring:
  application:
    name: microsesoft.hystrix.turbine
eureka:
  client:
    serviceUrl:    
      defaultZone: http://user:password123@localhost:8761/eureka/ 
  instance:
    prefer-ip-address: true
    metadata-map:  
      data: 我的自定义元数据movie
turbine: 
  appConfig: microservice-simple-consumer-movie-feign-hystrix-fallback-factory,microservice-consumer-movie-feign-hystrix-fallback-stream,microservice-simple-consumer-movie-robben-hystrix
  clusterNameExpression: "'default'"
      