server:
  port: 8021
spring:
  application:
    name: microservice-consumer-movie-feign-hystrix-fallback-stream
eureka:
  client:
    serviceUrl:    
      defaultZone: http://user:password123@localhost:8761/eureka/ 
  instance:
    prefer-ip-address: true
    metadata-map:  
      data: 我的自定义元数据movie
