server: 
  port: 8080
spring: 
  application:
    name: microsoft-config-serve-encryption
  cloud:
    config:
      server:
        git:
          uri: https://github.com/752143639/spring-cloud/  # 配置Git仓库的地址
         # label: dev
          username:                                                      
          password:  
        health:
          repositories:
            a-foo: 
              label: dev
              name: microservice-foo
              profiles: dev
encrypt:
  key: fooooo  # 设置对称密钥