server: 
  port: 8080
spring: 
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/752143639/spring-cloud/  # 配置Git仓库的地址
         # label: dev
          username:                                                      
          password:  
        health:
          repositories:
            a-foo: 
              label: dev
              name: microservice-foo
              profiles: dev
encrypt:
  keyStore:
    location: classpath:/server.jks # jks文件的路径
    password: letmein               # storepass
    alias: mytestkey                # alias
    secret: changeme                # keypass  